ちーずを追加
OthloTech/othlohack2019 pull request #8
Opened 2019-10-27 09:19 UTC by ShuzoTakahashi

2019-10-27 09:49 UTC, yoshikawa requested changes
画像サイズが7MBもあるので,圧縮かけてもらえると嬉しいです🙏

2019-10-27 10:50 UTC, ShuzoTakahashi commented
やっぱそうですよね。めんどくてな。

2019-10-27 10:52 UTC, yoshikawa commented
@ShuzoTakahashi めんどくさいのわかる(わかる)
ついでに, 他の重そうな画像も圧縮するかの気持ちでいる

2019-10-31 08:56 UTC, ShuzoTakahashi commented
🧀 が圧縮された。

2019-10-31 08:59 UTC, yoshikawa approved these changes
LGTM!!

2019-10-31 08:59 UTC, yoshikawa commented on index.html
> +            <h4>加藤 優奈</h4>
この人知ってます！

2019-10-31 09:00 UTC, merged